[package]
name = "radiolink"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7", features = ["critical-section-single-core"]}
cortex-m-rt = "0.7"
defmt-rtt = "0.4.0"
defmt = "0.3.5"
heapless = "0.7"
microbit = "0.13.0"
panic-halt = "0.2.0"
